package com.vixiloc.vixitask.presentations.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF5CE143)
val md_theme_dark_onPrimary = Color(0xFF043900)
val md_theme_dark_primaryContainer = Color(0xFF085300)
val md_theme_dark_onPrimaryContainer = Color(0xFF79FF5D)
val md_theme_dark_secondary = Color(0xFF85DA78)
val md_theme_dark_onSecondary = Color(0xFF003A03)
val md_theme_dark_secondaryContainer = Color(0xFF005307)
val md_theme_dark_onSecondaryContainer = Color(0xFFA1F791)
val md_theme_dark_tertiary = Color(0xFF3DDFA6)
val md_theme_dark_onTertiary = Color(0xFF003826)
val md_theme_dark_tertiaryContainer = Color(0xFF005139)
val md_theme_dark_onTertiaryContainer = Color(0xFF62FCC1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE2E3DC)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE2E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DC)
val md_theme_dark_inversePrimary = Color(0xFF0D6E00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5CE143)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)