package com.vixiloc.vixitask.presentations.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFC8BFFF)
val md_theme_dark_onPrimary = Color(0xFF2E2176)
val md_theme_dark_primaryContainer = Color(0xFF453A8D)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_secondary = Color(0xFFC9C3DC)
val md_theme_dark_onSecondary = Color(0xFF312E41)
val md_theme_dark_secondaryContainer = Color(0xFF474459)
val md_theme_dark_onSecondaryContainer = Color(0xFFE5DFF9)
val md_theme_dark_tertiary = Color(0xFFF4BF48)
val md_theme_dark_onTertiary = Color(0xFF402D00)
val md_theme_dark_tertiaryContainer = Color(0xFF5C4300)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEA1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF48464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val md_theme_dark_outline = Color(0xFF928F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF5D53A7)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC8BFFF)
val md_theme_dark_outlineVariant = Color(0xFF48464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFCEC6FF)
